language: node_js
node_js:
  - "12.8.0"
  
install:
  - npm i -g yarn && yarn install
  
script:
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master